### ISSUE TITLE
There are no such role in Galaxy

### ISSUE THREAD

**Issue by katoquro** [Aplyca/ansible-role-php#2]
ansible-galaxy install aplyca.PHP
- downloading role 'PHP', owned by aplyca
- sorry, aplyca.PHP was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.

**Comment by mauricios** [comment]
There is a problem with the Ansible Galaxy import, I'm starting to have this error in all my roles that previously were working:

```
FAILED:
Failed to find a README.md. All role repositories must include a README.md. Please refer to the 'Getting Started' documentation regarding role requirements. Once the issue has been corrected in the repsotitory, you can retry the import.
```

As you can see the README.md file is present in the root directory of the repo, I don't know what is wrong with the import process in Ansible Galaxy. Do you know where I can raise an issue on Ansible Galaxy or get support?

**Comment by katoquro** [comment]
I've found this one https://github.com/ansible/galaxy-issues

and as workaround I'm using:

```
# file requirements.yml
- src: aplyca.LAMP
- src: https://github.com/Aplyca/ansible-role-php/archive/v1.2.1.tar.gz
  name: aplyca.PHP
```

**Comment by mauricios** [comment]
Thanks for the galaxy issues site, I've found this issue reporting the problem with the README.md file https://github.com/ansible/galaxy-issues/issues/65

**Comment by mauricios** [comment]
The problem with README file in Ansible Galaxy was solved, the role is available now.
